Disable scheduled query auth0_brute_force.yml
I am disabling the scheduled query auth0_brute_force.yml because it caused issues for a customer [Error: failed to save query "Auth0 Brute Force Detection": 002003 (42S02): SQL compilation error:
Object 'PANTHER_LOGS.PUBLIC.AUTH0_EVENTS' does not exist or not authorized.]

In general, scheduled queries have to be disabled by default, because sometimes the scheduled queries might reference log types that the customers don't have, and this causes error messages.

Relevant discussions:
- Customer ticket: https://panther-labs.slack.com/archives/C05B9RZ2EG3/p1761774330368639
- Discussion in the ask ticket: https://panther-labs.slack.com/archives/C0719AH18SV/p1761842595369549